version: '3.8'
## docker compose file for development area
## see more comments by production config file in docker-compose.yml  
services:
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./nginx_dev.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - app
    networks:
      - internalnetwork

  maria_db:
    image: mariadb:11.4.2
    env_file: ./.env
    environment:
      - MARIADB_DATABASE=$DEV_MARIADB_DATABASE
      - MARIADB_USER=$DEV_MARIADB_USER
      - MARIADB_PASSWORD=$DEV_MARIADB_PASSWORD
    volumes:
      - data:/var/lib/mysql
      - ./init-dev.sql:/data/application/init-dev.sql
    command: --init-file /data/application/init-dev.sql
    ports:
      - $DEV_MARIADB_LOCAL_PORT:$DEV_MARIADB_DOCKER_PORT
    networks:
      - internalnetwork
    restart: unless-stopped

  app:
    image: selfcare-connection-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - "8443:8443"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://maria_db:$DEV_MARIADB_DOCKER_PORT/$DEV_MARIADB_DATABASE",
        "spring.datasource.username" : "$DEV_MARIADB_USER",
        "spring.datasource.password" : "$DEV_MARIADB_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MariaDBDialect",
        "spring.jpa.properties.hibernate.dialect.storage_engine" : "innodb",
        "spring.jpa.hibernate.ddl-auto" : "create"
       }'
    depends_on:
      - maria_db
    container_name: selfcare-connection-server
    networks:
      - internalnetwork
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  tests:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.m2:/root/.m2
    command: mvn test

networks:
  internalnetwork:
    driver: bridge

volumes:
  data:
