version: '3.8'
## docker compose configuration data for production mode
services:
  webserver: # nginx webserver to call service from outside
    image: nginx:alpine # light version of nginx
    container_name: webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # copy config file of nginx to container
      - /etc/letsencrypt/:/etc/letsencrypt/ # productive server reached by public domain and registered by letsencryt
    restart: unless-stopped # start again by crash or something else
    ports:
      - "443:443" # use encrypted https port to comunicate with website
    depends_on:
      - app # make sure that the docker-service 'app' is started too
    networks:
      - reverse-proxy-network # network for proxy for redirect to intern spring boot service

  maria_db:
    image: mariadb:11.4.2 # use the last version of mariaDB
    env_file: ./.env # watch config file .env and change there the data for live mode!
    environment:
      - MYSQL_DATABASE=$PROD_MYSQLDB_DATABASE
      - MYSQL_USER=$PROD_MYSQLDB_USER
      - MYSQL_PASSWORD=$PROD_MYSQLDB_PASSWORD # change credentials in .env
    ports:
      - $PROD_MYSQLDB_LOCAL_PORT:$PROD_MYSQLDB_DOCKER_PORT # port forwarding to standrad mariaDB port 
    networks:
      - internalnetwork # use only intern network for communication and never outside the server
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql # creator of database 
    command: --init-file /data/application/init.sql

  app:
    image: selfcare-connection-app # app service image name 
    build:
      context: .
      dockerfile: Dockerfile # name of configuration Dockerfile 
    env_file:
      - ./.env
    ports:
      - "8443:8443" # use only secure port with ssl protocol
    environment: # database data information and credentials you find in spring boot application properties
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://maria_db:$PROD_MYSQLDB_DOCKER_PORT/$PROD_MYSQLDB_DATABASE",
        "spring.datasource.username" : "$PROD_MYSQLDB_USER",
        "spring.datasource.password" : "$PROD_MYSQLDB_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.properties.hibernate.dialect.storage_engine" : "innodb",
        "spring.jpa.hibernate.ddl-auto" : "create"
       }'
    depends_on:
      - maria_db # docker service should only be started with database 
    container_name: selfcare-connection-server # container name of docker
    networks: # used networks for all containers 
      - reverse-proxy-network
      - internalnetwork
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

networks: # type of container networks
  internalnetwork: # used for internal container communication in bdidge mode
    driver: bridge
  reverse-proxy-network: # needed for external server communication by reverse proxy
    external:
      name: proxy-network

volumes:
  data: